name: Publish GH Pages

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ™
        uses: actions/checkout@v3
      - name: Nix â„ï¸
        uses: cachix/install-nix-action@v17
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Cachix ğŸ“¦
        uses: cachix/cachix-action@v10
        with:
          name: ners-ch
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - name: Build ğŸ”§
        run: nix build
      - name: Publish ğŸš€
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./result
